### ISSUE TITLE
Add meta tags for images to start linking social media previews directly

### ISSUE THREAD

**Issue by benjamminj** [benjamminj/portfolio#61]
- [x] Every post should have a unique `title` &  `description`
- [ ] Posts should have metadata to preview as Twitter cards
- [ ] Posts should have metadata to preview as LinkedIn cards
- [ ] Posts should have metadata to preview as FB cards?
- [ ] Posts should have keyword metadata
